### ISSUE TITLE
Should be dead simple

### ISSUE THREAD

**Issue by effigies** [nipreps/nipreps#2]
I don't think we want `nipreps.__version__`. It won't tell anybody anything useful, and we don't even really expect people to install this. I think even changing the namespace by adding `__version__` is more difference than I'd want in it being installed or not.

I'm okay with using tags for versioning, in which case hatch is better than flit, but if we're aren't going to change anything, we can go very bare-bones:

```diff
diff --git a/pyproject.toml b/pyproject.toml
new file mode 100644
index 0000000..fdccbb2
--- /dev/null
+++ b/pyproject.toml
@@ -0,0 +1,14 @@
+[build-system]
+requires = ["flit_core >=3.2,<4"]
+build-backend = "flit_core.buildapi"
+
+[project]
+name = "nipreps"
+version = "1.0"
+description = "Namespace package for nipreps utilities"
+authors = [{name = "The Nipreps developers", email = "nipreps@gmail.com"}]
+license = {file = "LICENSE"}
+classifiers = ["License :: OSI Approved :: Apache Software License"]
+
+[project.urls]
+Home = "https://nipreps.org"
diff --git a/src/nipreps/__init__.py b/src/nipreps/__init__.py
new file mode 100644
index 0000000..e69de29
```

I made this with `flit init` in ~20 seconds plus changing version and description from dynamic to static.

**Comment by mgxd** [comment]
One idea (down the line, as packages become available) would be to use this to store the relevant submodules (similar to [how templateflow is set up](https://github.com/templateflow/templateflow)), so as long as this build system wouldn't break then I'm for it.

Do you want to push these changes?

**Comment by effigies** [comment]
I thought this was just a namespace package and each (Python) submodule would be its own package. git submodules and Python submodules aren't really interchangeable, and I don't understand how to make something like templateflow work here. I'm also not sure why that's a goal. Possibly worth discussing this architecture in person?

**Comment by mgxd** [comment]
@oesteban and I were (loosely) discussing extracting out pieces of niworkflows to make installations more fine-grain - it was more of an idea than an outright goal, but I agree talking through the architecture during our next technical meeting sounds good. For now, I think we can proceed with your very minimal packaging.

**Comment by effigies** [comment]
Okay. I'll open a PR.
